version: "3"
services: 
  db-as:
    image: mariadb
    environment:.
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - twojVOLUMEN:/var/lib/mysql  

  adminer-as:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db-as
    ports:
      - TWOJPORT-8138:8080
### DODAJ kontener webapp bazujący na obrazie z7-TWOJLOGIN 
  webapp:
    image: z7-opszeniczko:1.0
    environment:
      - FLASK_RUN_HOST=localhost
      - FLASK_RUN_PORT=9999
      - FLASK_ENV=development
    ports:
      - 8038:9999
    volumes:
      - .:output
